# -*- coding: utf-8 -*-
"""Batminton_Player_Tracking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SI_nq-08q_BVTP3j9fH63KFmFvWQcM_v
"""

pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

import cv2
import torch
import numpy as np
import os
from torchvision.models.detection import keypointrcnn_resnet50_fpn


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = keypointrcnn_resnet50_fpn(pretrained=True).to(device)
model.eval()


SKELETON_CONNECTIONS = [
    (5,7), (7,9), (6,8), (8,10), (5,6),
    (5,11), (6,12), (11,12), (11,13), (13,15),
    (12,14), (14,16), (0,1), (0,2), (1,3), (2,4)
]

def draw_skeleton_on_frame(frame, keypoints):
    """Draw keypoints and skeleton lines."""
    for person in keypoints:
        for (i, j) in SKELETON_CONNECTIONS:
            if person[i][2] > 0 and person[j][2] > 0:
                x1, y1 = map(int, person[i][:2])
                x2, y2 = map(int, person[j][:2])
                cv2.line(frame, (x1, y1), (x2, y2), (0,255,0), 2)
        for (x, y, v) in person:
            if v > 0:
                cv2.circle(frame, (int(x), int(y)), 3, (0,0,255), -1)
    return frame



input_folder = "/content/drive/MyDrive/Videotest/Videos"
output_folder = "/content/drive/MyDrive/Videotest/Output"

os.makedirs(output_folder, exist_ok=True)


for i in range(1, 6):
    video_path = os.path.join(input_folder, f"{i}.mp4")
    output_path = os.path.join(output_folder, f"pose_{i}.mp4")

    if not os.path.exists(video_path):
        print(f"⚠️ Skipping {video_path} — file not found.")
        continue

    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(
        output_path, fourcc, 20.0,
        (int(cap.get(3)), int(cap.get(4)))
    )

    frame_count = 0
    print(f"⏳ Processing video {i}.mp4 ...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1


        img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        img_tensor = torch.from_numpy(img / 255.).permute(2,0,1).float().to(device)


        with torch.no_grad():
            outputs = model([img_tensor])[0]


        keypoints = outputs['keypoints'][outputs['scores'] > 0.9].cpu().numpy()
        frame = draw_skeleton_on_frame(frame, keypoints)

        out.write(frame)

    cap.release()
    out.release()
    print(f"✅ Finished {i}.mp4 — processed {frame_count} frames. Saved to {output_path}")

print("🎉 Pose detection completed for all 5 videos!")

from ultralytics import YOLO
import os


model = YOLO("yolov8n.pt")


model.info()


results = model.train(
    data="/content/drive/MyDrive/Batminton Player Tracking.v2i.yolov8/data.yaml",
    epochs=30,
    imgsz=640,
    project="/content/drive/MyDrive/Batminton Player Tracking.v2i.yolov8",
    name="batminton_yolov8n"
)


trained_model_path = "/content/drive/MyDrive/Batminton Player Tracking.v2i.yolov8/batminton_yolov8n/weights/best.pt"


if os.path.exists(trained_model_path):
    print(f"✅ Trained model saved successfully at: {trained_model_path}")
else:
    raise FileNotFoundError("❌ Trained model not found. Please check the training folder path.")

trained_model = YOLO(trained_model_path)

video_folder = "/content/drive/MyDrive/Batminton Player Tracking.v2i.yolov8/test/videos"


output_dir = "/content/drive/MyDrive/Batminton Player Tracking.v2i.yolov8/predictions/videos"
os.makedirs(output_dir, exist_ok=True)


for i in range(1, 6):
    video_path = os.path.join(video_folder, f"{i}.mp4")
    if os.path.exists(video_path):
        print(f"🎬 Running prediction on video {i}.mp4 ...")
        trained_model.predict(
            source=video_path,
            save=True,
            save_conf=True,
            project=output_dir,
            name=f"video_{i}_results"
        )
        print(f" Prediction completed for video {i}.mp4")
    else:
        print(f" Video {i}.mp4 not found in {video_folder}")

print(" All available videos processed successfully!")